name: Create Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      #   - name: Ensure tag is on main or dev branch
      #     run: |
      #       git fetch origin main dev
      #       if git merge-base --is-ancestor $GITHUB_SHA origin/main; then
      #         echo "Tag is on main branch."
      #       elif git merge-base --is-ancestor $GITHUB_SHA origin/dev; then
      #         echo "Tag is on dev branch."
      #       else
      #         echo "Tag is not on main or dev branch. Exiting."
      #         exit 1
      #       fi

      - name: Detect prerelease
        id: prerelease
        run: |
          TAG="${GITHUB_REF_NAME}"
          if [[ "$TAG" == *"-rc"* || "$TAG" == *"-beta"* || "$TAG" == *"-alpha"* ]]; then
            echo "prerelease=true" >> $GITHUB_OUTPUT
          else
            echo "prerelease=false" >> $GITHUB_OUTPUT
          fi

      - name: Generate changelog
        uses: orhun/git-cliff-action@v4
        id: changelog
        with:
          config: .github/cliff.toml
          args: --latest --strip header
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: |
            ${{ steps.changelog.outputs.content }}
          prerelease: ${{ steps.prerelease.outputs.prerelease }}
          generate_release_notes: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
